# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from kentik.mkp.v202102alpha1 import \
    mkp_pb2 as kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2


class PackageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPackage = channel.unary_unary(
                '/kentik.mkp.v202102alpha1.PackageService/ListPackage',
                request_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.ListPackageRequest.SerializeToString,
                response_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.ListPackageResponse.FromString,
                )
        self.GetPackage = channel.unary_unary(
                '/kentik.mkp.v202102alpha1.PackageService/GetPackage',
                request_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.GetPackageRequest.SerializeToString,
                response_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.GetPackageResponse.FromString,
                )
        self.CreatePackage = channel.unary_unary(
                '/kentik.mkp.v202102alpha1.PackageService/CreatePackage',
                request_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.CreatePackageRequest.SerializeToString,
                response_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.CreatePackageResponse.FromString,
                )
        self.UpdatePackage = channel.unary_unary(
                '/kentik.mkp.v202102alpha1.PackageService/UpdatePackage',
                request_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.UpdatePackageRequest.SerializeToString,
                response_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.UpdatePackageResponse.FromString,
                )
        self.PatchPackage = channel.unary_unary(
                '/kentik.mkp.v202102alpha1.PackageService/PatchPackage',
                request_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.PatchPackageRequest.SerializeToString,
                response_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.PatchPackageResponse.FromString,
                )
        self.DeletePackage = channel.unary_unary(
                '/kentik.mkp.v202102alpha1.PackageService/DeletePackage',
                request_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.DeletePackageRequest.SerializeToString,
                response_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.DeletePackageResponse.FromString,
                )


class PackageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListPackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchPackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PackageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPackage': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPackage,
                    request_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.ListPackageRequest.FromString,
                    response_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.ListPackageResponse.SerializeToString,
            ),
            'GetPackage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPackage,
                    request_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.GetPackageRequest.FromString,
                    response_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.GetPackageResponse.SerializeToString,
            ),
            'CreatePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePackage,
                    request_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.CreatePackageRequest.FromString,
                    response_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.CreatePackageResponse.SerializeToString,
            ),
            'UpdatePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePackage,
                    request_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.UpdatePackageRequest.FromString,
                    response_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.UpdatePackageResponse.SerializeToString,
            ),
            'PatchPackage': grpc.unary_unary_rpc_method_handler(
                    servicer.PatchPackage,
                    request_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.PatchPackageRequest.FromString,
                    response_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.PatchPackageResponse.SerializeToString,
            ),
            'DeletePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePackage,
                    request_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.DeletePackageRequest.FromString,
                    response_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.DeletePackageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kentik.mkp.v202102alpha1.PackageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PackageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListPackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.mkp.v202102alpha1.PackageService/ListPackage',
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.ListPackageRequest.SerializeToString,
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.ListPackageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.mkp.v202102alpha1.PackageService/GetPackage',
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.GetPackageRequest.SerializeToString,
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.GetPackageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.mkp.v202102alpha1.PackageService/CreatePackage',
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.CreatePackageRequest.SerializeToString,
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.CreatePackageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.mkp.v202102alpha1.PackageService/UpdatePackage',
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.UpdatePackageRequest.SerializeToString,
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.UpdatePackageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PatchPackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.mkp.v202102alpha1.PackageService/PatchPackage',
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.PatchPackageRequest.SerializeToString,
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.PatchPackageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.mkp.v202102alpha1.PackageService/DeletePackage',
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.DeletePackageRequest.SerializeToString,
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.DeletePackageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class TenantServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTenant = channel.unary_unary(
                '/kentik.mkp.v202102alpha1.TenantService/ListTenant',
                request_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.ListTenantRequest.SerializeToString,
                response_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.ListTenantResponse.FromString,
                )
        self.GetTenant = channel.unary_unary(
                '/kentik.mkp.v202102alpha1.TenantService/GetTenant',
                request_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.GetTenantRequest.SerializeToString,
                response_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.GetTenantResponse.FromString,
                )
        self.CreateTenant = channel.unary_unary(
                '/kentik.mkp.v202102alpha1.TenantService/CreateTenant',
                request_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.CreateTenantRequest.SerializeToString,
                response_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.CreateTenantResponse.FromString,
                )
        self.UpdateTenant = channel.unary_unary(
                '/kentik.mkp.v202102alpha1.TenantService/UpdateTenant',
                request_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.UpdateTenantRequest.SerializeToString,
                response_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.UpdateTenantResponse.FromString,
                )
        self.PatchTenant = channel.unary_unary(
                '/kentik.mkp.v202102alpha1.TenantService/PatchTenant',
                request_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.PatchTenantRequest.SerializeToString,
                response_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.PatchTenantResponse.FromString,
                )
        self.DeleteTenant = channel.unary_unary(
                '/kentik.mkp.v202102alpha1.TenantService/DeleteTenant',
                request_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.DeleteTenantRequest.SerializeToString,
                response_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.DeleteTenantResponse.FromString,
                )


class TenantServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TenantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTenant,
                    request_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.ListTenantRequest.FromString,
                    response_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.ListTenantResponse.SerializeToString,
            ),
            'GetTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenant,
                    request_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.GetTenantRequest.FromString,
                    response_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.GetTenantResponse.SerializeToString,
            ),
            'CreateTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTenant,
                    request_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.CreateTenantRequest.FromString,
                    response_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.CreateTenantResponse.SerializeToString,
            ),
            'UpdateTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTenant,
                    request_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.UpdateTenantRequest.FromString,
                    response_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.UpdateTenantResponse.SerializeToString,
            ),
            'PatchTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.PatchTenant,
                    request_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.PatchTenantRequest.FromString,
                    response_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.PatchTenantResponse.SerializeToString,
            ),
            'DeleteTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTenant,
                    request_deserializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.DeleteTenantRequest.FromString,
                    response_serializer=kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.DeleteTenantResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kentik.mkp.v202102alpha1.TenantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TenantService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.mkp.v202102alpha1.TenantService/ListTenant',
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.ListTenantRequest.SerializeToString,
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.ListTenantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.mkp.v202102alpha1.TenantService/GetTenant',
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.GetTenantRequest.SerializeToString,
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.GetTenantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.mkp.v202102alpha1.TenantService/CreateTenant',
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.CreateTenantRequest.SerializeToString,
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.CreateTenantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.mkp.v202102alpha1.TenantService/UpdateTenant',
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.UpdateTenantRequest.SerializeToString,
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.UpdateTenantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PatchTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.mkp.v202102alpha1.TenantService/PatchTenant',
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.PatchTenantRequest.SerializeToString,
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.PatchTenantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.mkp.v202102alpha1.TenantService/DeleteTenant',
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.DeleteTenantRequest.SerializeToString,
            kentik_dot_mkp_dot_v202102alpha1_dot_mkp__pb2.DeleteTenantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
