# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from kentik.synthetics.backend.v1 import \
    synthetics_pb2 as \
    kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2


class SyntheticAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Auth = channel.unary_unary(
                '/synthetic.SyntheticAgent/Auth',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.AuthRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.AuthReply.FromString,
                )
        self.Tasks = channel.unary_unary(
                '/synthetic.SyntheticAgent/Tasks',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.TasksRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.TasksReply.FromString,
                )
        self.Status = channel.unary_unary(
                '/synthetic.SyntheticAgent/Status',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.StatusRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.StatusReply.FromString,
                )
        self.Deauth = channel.unary_unary(
                '/synthetic.SyntheticAgent/Deauth',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.DeauthRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.DeauthReply.FromString,
                )
        self.Search = channel.unary_unary(
                '/synthetic.SyntheticAgent/Search',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.SearchRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.SearchReply.FromString,
                )
        self.UpdateAgent = channel.unary_unary(
                '/synthetic.SyntheticAgent/UpdateAgent',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateAgentRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateAgentReply.FromString,
                )
        self.UpdateTask = channel.unary_unary(
                '/synthetic.SyntheticAgent/UpdateTask',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateTaskRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateTaskReply.FromString,
                )
        self.AgentTaskAssign = channel.unary_unary(
                '/synthetic.SyntheticAgent/AgentTaskAssign',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.AgentTaskAssignRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.AgentTaskAssignReply.FromString,
                )
        self.UpdateTest = channel.unary_unary(
                '/synthetic.SyntheticAgent/UpdateTest',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateTestRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateTestReply.FromString,
                )
        self.SetTasksFromTests = channel.unary_unary(
                '/synthetic.SyntheticAgent/SetTasksFromTests',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.SetTasksFromTestsRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.SetTasksFromTestsReply.FromString,
                )
        self.GetHealthForTests = channel.unary_unary(
                '/synthetic.SyntheticAgent/GetHealthForTests',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetHealthForTestsRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetHealthForTestsReply.FromString,
                )
        self.GetTraceForTest = channel.unary_unary(
                '/synthetic.SyntheticAgent/GetTraceForTest',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetTraceForTestRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetTraceForTestReply.FromString,
                )
        self.DropAgentCache = channel.unary_unary(
                '/synthetic.SyntheticAgent/DropAgentCache',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.DropAgentCacheRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.DropAgentCacheReply.FromString,
                )
        self.GetHealthOfAgents = channel.unary_unary(
                '/synthetic.SyntheticAgent/GetHealthOfAgents',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetHealthOfAgentsRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetHealthOfAgentsReply.FromString,
                )
        self.GetErrorsForTests = channel.unary_unary(
                '/synthetic.SyntheticAgent/GetErrorsForTests',
                request_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetErrorsForTestsRequest.SerializeToString,
                response_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetErrorsForTestsReply.FromString,
                )


class SyntheticAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Auth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deauth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentTaskAssign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTasksFromTests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealthForTests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTraceForTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropAgentCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealthOfAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrorsForTests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyntheticAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Auth': grpc.unary_unary_rpc_method_handler(
                    servicer.Auth,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.AuthRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.AuthReply.SerializeToString,
            ),
            'Tasks': grpc.unary_unary_rpc_method_handler(
                    servicer.Tasks,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.TasksRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.TasksReply.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.StatusRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.StatusReply.SerializeToString,
            ),
            'Deauth': grpc.unary_unary_rpc_method_handler(
                    servicer.Deauth,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.DeauthRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.DeauthReply.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.SearchRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.SearchReply.SerializeToString,
            ),
            'UpdateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAgent,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateAgentRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateAgentReply.SerializeToString,
            ),
            'UpdateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTask,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateTaskRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateTaskReply.SerializeToString,
            ),
            'AgentTaskAssign': grpc.unary_unary_rpc_method_handler(
                    servicer.AgentTaskAssign,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.AgentTaskAssignRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.AgentTaskAssignReply.SerializeToString,
            ),
            'UpdateTest': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTest,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateTestRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateTestReply.SerializeToString,
            ),
            'SetTasksFromTests': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTasksFromTests,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.SetTasksFromTestsRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.SetTasksFromTestsReply.SerializeToString,
            ),
            'GetHealthForTests': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealthForTests,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetHealthForTestsRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetHealthForTestsReply.SerializeToString,
            ),
            'GetTraceForTest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTraceForTest,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetTraceForTestRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetTraceForTestReply.SerializeToString,
            ),
            'DropAgentCache': grpc.unary_unary_rpc_method_handler(
                    servicer.DropAgentCache,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.DropAgentCacheRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.DropAgentCacheReply.SerializeToString,
            ),
            'GetHealthOfAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealthOfAgents,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetHealthOfAgentsRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetHealthOfAgentsReply.SerializeToString,
            ),
            'GetErrorsForTests': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrorsForTests,
                    request_deserializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetErrorsForTestsRequest.FromString,
                    response_serializer=kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetErrorsForTestsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synthetic.SyntheticAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SyntheticAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Auth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/Auth',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.AuthRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.AuthReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Tasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/Tasks',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.TasksRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.TasksReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/Status',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.StatusRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.StatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Deauth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/Deauth',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.DeauthRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.DeauthReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/Search',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.SearchRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.SearchReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/UpdateAgent',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateAgentRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateAgentReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/UpdateTask',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateTaskRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateTaskReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AgentTaskAssign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/AgentTaskAssign',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.AgentTaskAssignRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.AgentTaskAssignReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/UpdateTest',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateTestRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.UpdateTestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTasksFromTests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/SetTasksFromTests',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.SetTasksFromTestsRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.SetTasksFromTestsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHealthForTests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/GetHealthForTests',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetHealthForTestsRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetHealthForTestsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTraceForTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/GetTraceForTest',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetTraceForTestRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetTraceForTestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DropAgentCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/DropAgentCache',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.DropAgentCacheRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.DropAgentCacheReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHealthOfAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/GetHealthOfAgents',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetHealthOfAgentsRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetHealthOfAgentsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetErrorsForTests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthetic.SyntheticAgent/GetErrorsForTests',
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetErrorsForTestsRequest.SerializeToString,
            kentik_dot_synthetics_dot_backend_dot_v1_dot_synthetics__pb2.GetErrorsForTestsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
