# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kentik/core/v202012alpha1/errors.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import \
    timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from protoc_gen_openapiv2.options import \
    annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='kentik/core/v202012alpha1/errors.proto',
  package='kentik.core.v202012alpha1',
  syntax='proto3',
  serialized_options=b'ZHgithub.com/kentik/api-schema/gen/go/kentik/core/v202012alpha1;kentik_api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&kentik/core/v202012alpha1/errors.proto\x12\x19kentik.core.v202012alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xca\x02\n\tErrorInfo\x12\x1d\n\x04\x63ode\x18\x01 \x01(\x05\x42\x0f\x92\x41\x0c\x32\nError code\x12#\n\x07message\x18\x02 \x01(\tB\x12\x92\x41\x0f\x32\rError message\x12H\n\x0e\x63orrelation_id\x18\x03 \x01(\tB0\x92\x41-2+Unique event identifier for server requests\x12Y\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB*\x92\x41\'2%Date and time when this error occured\x12T\n\x12\x64ocumentation_link\x18\x05 \x01(\tB8\x92\x41\x35\x32\x33Optional link to documentation regarding this errorBJZHgithub.com/kentik/api-schema/gen/go/kentik/core/v202012alpha1;kentik_apib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,protoc__gen__openapiv2_dot_options_dot_annotations__pb2.DESCRIPTOR,])




_ERRORINFO = _descriptor.Descriptor(
  name='ErrorInfo',
  full_name='kentik.core.v202012alpha1.ErrorInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='kentik.core.v202012alpha1.ErrorInfo.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222A\0142\nError code', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='kentik.core.v202012alpha1.ErrorInfo.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222A\0172\rError message', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='correlation_id', full_name='kentik.core.v202012alpha1.ErrorInfo.correlation_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222A-2+Unique event identifier for server requests', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='kentik.core.v202012alpha1.ErrorInfo.timestamp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222A\'2%Date and time when this error occured', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='documentation_link', full_name='kentik.core.v202012alpha1.ErrorInfo.documentation_link', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222A523Optional link to documentation regarding this error', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=481,
)

_ERRORINFO.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ErrorInfo'] = _ERRORINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ErrorInfo = _reflection.GeneratedProtocolMessageType('ErrorInfo', (_message.Message,), {
  'DESCRIPTOR' : _ERRORINFO,
  '__module__' : 'kentik.core.v202012alpha1.errors_pb2'
  # @@protoc_insertion_point(class_scope:kentik.core.v202012alpha1.ErrorInfo)
  })
_sym_db.RegisterMessage(ErrorInfo)


DESCRIPTOR._options = None
_ERRORINFO.fields_by_name['code']._options = None
_ERRORINFO.fields_by_name['message']._options = None
_ERRORINFO.fields_by_name['correlation_id']._options = None
_ERRORINFO.fields_by_name['timestamp']._options = None
_ERRORINFO.fields_by_name['documentation_link']._options = None
# @@protoc_insertion_point(module_scope)
