# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kentik/core/v202012alpha1/kentik_types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import \
    timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='kentik/core/v202012alpha1/kentik_types.proto',
  package='kentik.core.v202012alpha1',
  syntax='proto3',
  serialized_options=b'ZHgithub.com/kentik/api-schema/gen/go/kentik/core/v202012alpha1;kentik_api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,kentik/core/v202012alpha1/kentik_types.proto\x12\x19kentik.core.v202012alpha1\x1a\x1fgoogle/protobuf/timestamp.protoBJZHgithub.com/kentik/api-schema/gen/go/kentik/core/v202012alpha1;kentik_apib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
