# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from kentik.user.v202106alpha1 import \
    user_pb2 as kentik_dot_user_dot_v202106alpha1_dot_user__pb2


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUser = channel.unary_unary(
                '/kentik.user.v202106alpha1.UserService/ListUser',
                request_serializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.ListUserRequest.SerializeToString,
                response_deserializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.ListUserResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/kentik.user.v202106alpha1.UserService/GetUser',
                request_serializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.GetUserResponse.FromString,
                )
        self.CreateUser = channel.unary_unary(
                '/kentik.user.v202106alpha1.UserService/CreateUser',
                request_serializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.CreateUserResponse.FromString,
                )
        self.UpdateUser = channel.unary_unary(
                '/kentik.user.v202106alpha1.UserService/UpdateUser',
                request_serializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.UpdateUserResponse.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/kentik.user.v202106alpha1.UserService/DeleteUser',
                request_serializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.DeleteUserResponse.FromString,
                )


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUser,
                    request_deserializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.ListUserRequest.FromString,
                    response_serializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.ListUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.GetUserResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.CreateUserRequest.FromString,
                    response_serializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.CreateUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.UpdateUserRequest.FromString,
                    response_serializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.UpdateUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.DeleteUserRequest.FromString,
                    response_serializer=kentik_dot_user_dot_v202106alpha1_dot_user__pb2.DeleteUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kentik.user.v202106alpha1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.user.v202106alpha1.UserService/ListUser',
            kentik_dot_user_dot_v202106alpha1_dot_user__pb2.ListUserRequest.SerializeToString,
            kentik_dot_user_dot_v202106alpha1_dot_user__pb2.ListUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.user.v202106alpha1.UserService/GetUser',
            kentik_dot_user_dot_v202106alpha1_dot_user__pb2.GetUserRequest.SerializeToString,
            kentik_dot_user_dot_v202106alpha1_dot_user__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.user.v202106alpha1.UserService/CreateUser',
            kentik_dot_user_dot_v202106alpha1_dot_user__pb2.CreateUserRequest.SerializeToString,
            kentik_dot_user_dot_v202106alpha1_dot_user__pb2.CreateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.user.v202106alpha1.UserService/UpdateUser',
            kentik_dot_user_dot_v202106alpha1_dot_user__pb2.UpdateUserRequest.SerializeToString,
            kentik_dot_user_dot_v202106alpha1_dot_user__pb2.UpdateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.user.v202106alpha1.UserService/DeleteUser',
            kentik_dot_user_dot_v202106alpha1_dot_user__pb2.DeleteUserRequest.SerializeToString,
            kentik_dot_user_dot_v202106alpha1_dot_user__pb2.DeleteUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
