# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from kentik.network_class.v202109alpha1 import \
    network_class_pb2 as \
    kentik_dot_network__class_dot_v202109alpha1_dot_network__class__pb2


class NetworkClassServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNetworkClass = channel.unary_unary(
                '/kentik.network_class.v202109alpha1.NetworkClassService/GetNetworkClass',
                request_serializer=kentik_dot_network__class_dot_v202109alpha1_dot_network__class__pb2.GetNetworkClassRequest.SerializeToString,
                response_deserializer=kentik_dot_network__class_dot_v202109alpha1_dot_network__class__pb2.GetNetworkClassResponse.FromString,
                )
        self.UpdateNetworkClass = channel.unary_unary(
                '/kentik.network_class.v202109alpha1.NetworkClassService/UpdateNetworkClass',
                request_serializer=kentik_dot_network__class_dot_v202109alpha1_dot_network__class__pb2.UpdateNetworkClassRequest.SerializeToString,
                response_deserializer=kentik_dot_network__class_dot_v202109alpha1_dot_network__class__pb2.UpdateNetworkClassResponse.FromString,
                )


class NetworkClassServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNetworkClass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNetworkClass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkClassServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNetworkClass': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkClass,
                    request_deserializer=kentik_dot_network__class_dot_v202109alpha1_dot_network__class__pb2.GetNetworkClassRequest.FromString,
                    response_serializer=kentik_dot_network__class_dot_v202109alpha1_dot_network__class__pb2.GetNetworkClassResponse.SerializeToString,
            ),
            'UpdateNetworkClass': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNetworkClass,
                    request_deserializer=kentik_dot_network__class_dot_v202109alpha1_dot_network__class__pb2.UpdateNetworkClassRequest.FromString,
                    response_serializer=kentik_dot_network__class_dot_v202109alpha1_dot_network__class__pb2.UpdateNetworkClassResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kentik.network_class.v202109alpha1.NetworkClassService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NetworkClassService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNetworkClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.network_class.v202109alpha1.NetworkClassService/GetNetworkClass',
            kentik_dot_network__class_dot_v202109alpha1_dot_network__class__pb2.GetNetworkClassRequest.SerializeToString,
            kentik_dot_network__class_dot_v202109alpha1_dot_network__class__pb2.GetNetworkClassResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateNetworkClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.network_class.v202109alpha1.NetworkClassService/UpdateNetworkClass',
            kentik_dot_network__class_dot_v202109alpha1_dot_network__class__pb2.UpdateNetworkClassRequest.SerializeToString,
            kentik_dot_network__class_dot_v202109alpha1_dot_network__class__pb2.UpdateNetworkClassResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
