# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from kentik.interface.v202108alpha1 import \
    interface_pb2 as kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2


class InterfaceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ManualClassify = channel.unary_unary(
                '/kentik.interface.v202108alpha1.InterfaceService/ManualClassify',
                request_serializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.ManualClassifyRequest.SerializeToString,
                response_deserializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.ManualClassifyResponse.FromString,
                )
        self.ListInterface = channel.unary_unary(
                '/kentik.interface.v202108alpha1.InterfaceService/ListInterface',
                request_serializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.ListInterfaceRequest.SerializeToString,
                response_deserializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.ListInterfaceResponse.FromString,
                )
        self.GetInterface = channel.unary_unary(
                '/kentik.interface.v202108alpha1.InterfaceService/GetInterface',
                request_serializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.GetInterfaceRequest.SerializeToString,
                response_deserializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.GetInterfaceResponse.FromString,
                )
        self.CreateInterface = channel.unary_unary(
                '/kentik.interface.v202108alpha1.InterfaceService/CreateInterface',
                request_serializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.CreateInterfaceRequest.SerializeToString,
                response_deserializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.CreateInterfaceResponse.FromString,
                )
        self.UpdateInterface = channel.unary_unary(
                '/kentik.interface.v202108alpha1.InterfaceService/UpdateInterface',
                request_serializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.UpdateInterfaceRequest.SerializeToString,
                response_deserializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.UpdateInterfaceResponse.FromString,
                )
        self.DeleteInterface = channel.unary_unary(
                '/kentik.interface.v202108alpha1.InterfaceService/DeleteInterface',
                request_serializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.DeleteInterfaceRequest.SerializeToString,
                response_deserializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.DeleteInterfaceResponse.FromString,
                )


class InterfaceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ManualClassify(self, request, context):
        """Comment out for now until we need auto classification.
        rpc AutoClassify(AutoClassifyRequest) returns (AutoClassifyResponse) {
        option (kentik.core.v202012alpha1.method_scope) = "admin.interface:write";
        option (google.api.http) = {
        get: "/interface/v202108alpha1/auto_classify"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        operation_id: "AutoClassify"
        summary: "Auto Classify Interface"
        description: "Classify devices and interface base on rules."
        };
        }

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInterface(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterface(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInterface(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInterface(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInterface(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InterfaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ManualClassify': grpc.unary_unary_rpc_method_handler(
                    servicer.ManualClassify,
                    request_deserializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.ManualClassifyRequest.FromString,
                    response_serializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.ManualClassifyResponse.SerializeToString,
            ),
            'ListInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInterface,
                    request_deserializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.ListInterfaceRequest.FromString,
                    response_serializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.ListInterfaceResponse.SerializeToString,
            ),
            'GetInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterface,
                    request_deserializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.GetInterfaceRequest.FromString,
                    response_serializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.GetInterfaceResponse.SerializeToString,
            ),
            'CreateInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInterface,
                    request_deserializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.CreateInterfaceRequest.FromString,
                    response_serializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.CreateInterfaceResponse.SerializeToString,
            ),
            'UpdateInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInterface,
                    request_deserializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.UpdateInterfaceRequest.FromString,
                    response_serializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.UpdateInterfaceResponse.SerializeToString,
            ),
            'DeleteInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInterface,
                    request_deserializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.DeleteInterfaceRequest.FromString,
                    response_serializer=kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.DeleteInterfaceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kentik.interface.v202108alpha1.InterfaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InterfaceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ManualClassify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.interface.v202108alpha1.InterfaceService/ManualClassify',
            kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.ManualClassifyRequest.SerializeToString,
            kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.ManualClassifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.interface.v202108alpha1.InterfaceService/ListInterface',
            kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.ListInterfaceRequest.SerializeToString,
            kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.ListInterfaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.interface.v202108alpha1.InterfaceService/GetInterface',
            kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.GetInterfaceRequest.SerializeToString,
            kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.GetInterfaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.interface.v202108alpha1.InterfaceService/CreateInterface',
            kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.CreateInterfaceRequest.SerializeToString,
            kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.CreateInterfaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.interface.v202108alpha1.InterfaceService/UpdateInterface',
            kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.UpdateInterfaceRequest.SerializeToString,
            kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.UpdateInterfaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.interface.v202108alpha1.InterfaceService/DeleteInterface',
            kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.DeleteInterfaceRequest.SerializeToString,
            kentik_dot_interface_dot_v202108alpha1_dot_interface__pb2.DeleteInterfaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
