# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from kentik.cloud_export.v202101beta1 import \
    cloud_export_pb2 as \
    kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2


class CloudExportAdminServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCloudExport = channel.unary_unary(
                '/kentik.cloud_export.v202101beta1.CloudExportAdminService/CreateCloudExport',
                request_serializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.CreateCloudExportRequest.SerializeToString,
                response_deserializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.CreateCloudExportResponse.FromString,
                )
        self.ListCloudExport = channel.unary_unary(
                '/kentik.cloud_export.v202101beta1.CloudExportAdminService/ListCloudExport',
                request_serializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.ListCloudExportRequest.SerializeToString,
                response_deserializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.ListCloudExportResponse.FromString,
                )
        self.GetCloudExport = channel.unary_unary(
                '/kentik.cloud_export.v202101beta1.CloudExportAdminService/GetCloudExport',
                request_serializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.GetCloudExportRequest.SerializeToString,
                response_deserializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.GetCloudExportResponse.FromString,
                )
        self.PatchCloudExport = channel.unary_unary(
                '/kentik.cloud_export.v202101beta1.CloudExportAdminService/PatchCloudExport',
                request_serializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.PatchCloudExportRequest.SerializeToString,
                response_deserializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.PatchCloudExportResponse.FromString,
                )
        self.UpdateCloudExport = channel.unary_unary(
                '/kentik.cloud_export.v202101beta1.CloudExportAdminService/UpdateCloudExport',
                request_serializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.UpdateCloudExportRequest.SerializeToString,
                response_deserializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.UpdateCloudExportResponse.FromString,
                )
        self.DeleteCloudExport = channel.unary_unary(
                '/kentik.cloud_export.v202101beta1.CloudExportAdminService/DeleteCloudExport',
                request_serializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.DeleteCloudExportRequest.SerializeToString,
                response_deserializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.DeleteCloudExportResponse.FromString,
                )


class CloudExportAdminServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCloudExport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCloudExport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCloudExport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchCloudExport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCloudExport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCloudExport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudExportAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCloudExport': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCloudExport,
                    request_deserializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.CreateCloudExportRequest.FromString,
                    response_serializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.CreateCloudExportResponse.SerializeToString,
            ),
            'ListCloudExport': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCloudExport,
                    request_deserializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.ListCloudExportRequest.FromString,
                    response_serializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.ListCloudExportResponse.SerializeToString,
            ),
            'GetCloudExport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCloudExport,
                    request_deserializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.GetCloudExportRequest.FromString,
                    response_serializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.GetCloudExportResponse.SerializeToString,
            ),
            'PatchCloudExport': grpc.unary_unary_rpc_method_handler(
                    servicer.PatchCloudExport,
                    request_deserializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.PatchCloudExportRequest.FromString,
                    response_serializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.PatchCloudExportResponse.SerializeToString,
            ),
            'UpdateCloudExport': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCloudExport,
                    request_deserializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.UpdateCloudExportRequest.FromString,
                    response_serializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.UpdateCloudExportResponse.SerializeToString,
            ),
            'DeleteCloudExport': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCloudExport,
                    request_deserializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.DeleteCloudExportRequest.FromString,
                    response_serializer=kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.DeleteCloudExportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kentik.cloud_export.v202101beta1.CloudExportAdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CloudExportAdminService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCloudExport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.cloud_export.v202101beta1.CloudExportAdminService/CreateCloudExport',
            kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.CreateCloudExportRequest.SerializeToString,
            kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.CreateCloudExportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCloudExport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.cloud_export.v202101beta1.CloudExportAdminService/ListCloudExport',
            kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.ListCloudExportRequest.SerializeToString,
            kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.ListCloudExportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCloudExport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.cloud_export.v202101beta1.CloudExportAdminService/GetCloudExport',
            kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.GetCloudExportRequest.SerializeToString,
            kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.GetCloudExportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PatchCloudExport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.cloud_export.v202101beta1.CloudExportAdminService/PatchCloudExport',
            kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.PatchCloudExportRequest.SerializeToString,
            kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.PatchCloudExportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCloudExport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.cloud_export.v202101beta1.CloudExportAdminService/UpdateCloudExport',
            kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.UpdateCloudExportRequest.SerializeToString,
            kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.UpdateCloudExportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCloudExport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kentik.cloud_export.v202101beta1.CloudExportAdminService/DeleteCloudExport',
            kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.DeleteCloudExportRequest.SerializeToString,
            kentik_dot_cloud__export_dot_v202101beta1_dot_cloud__export__pb2.DeleteCloudExportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
