name: build

# Run this workflow all on pushes to main
on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ 'main' ]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build-packages:
    uses: ./.github/workflows/build_packages.yml

  package-tests:
    runs-on: ubuntu-latest
    needs: [ build-packages ]
    strategy: 
      matrix:
        version: ${{ fromJson(vars.PYTHON_VERSIONS) }}
    steps:
      - name: Prepare python env
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
          architecture: x64
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts.python${{ matrix.version }}
          path: artifacts
      - name: Install lib from package
        run: |
          pip install artifacts/dist/*.whl
      - name: Show installed packages
        run: pip freeze
      - name: Check if import is possible
        run: |
          for package in kentik_api kentik_api.auth kentik_api.api_calls
          do
            python artifacts/tests/library/test_imports.py ${package}
            echo "Imported package: ${package}"
          done
