name: build_packages

# Run only when called from another workflow
on:
  workflow_call:
    inputs:
      python_versions:
        description: "List of Python versions for which to build packages"
        default: ${{ vars.PYTHON_VERSIONS }}
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(inputs.python_versions) }}
    steps:
      - name: (HELPER) Checkout Code
        uses: actions/checkout@v3
      - name: Prepare python env
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
          architecture: x64
      - name: Build package
        run: |
          pip3 install -r requirements.txt
          pip3 install -r requirements-dev.txt
          python3 setup.py grpc_stubs # building grpc stubs must go before building
          python3 -m build
      - name: Archive code
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.gz
          retention-days: 5
      - name: Archive package
        uses: actions/upload-artifact@v3
        with:
          name: artifacts.python${{ matrix.version}}
          path: |
            dist/
            tests/library/test_imports.py
          retention-days: 5
