name: release

on:
  release:
    types: [published]

jobs:
  build-packages:
    uses: ./.github/workflows/build_packages.yml
    with:
      python_versions: ${{ vars.RELEASE_PYTHON_VERSION }}

  # Publish packages to PyPi
  publish-packages:
    needs: [ build-packages ]
    runs-on: ubuntu-latest
    steps:
      - name: Prepare python env
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.RELEASE_PYTHON_VERSION }}
          architecture: x64
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts.python${{ vars.RELEASE_PYTHON_VERSION }}
          path: artifacts
      - name: Push package to PyPi
        run: |
          python3 -m pip install --user --upgrade twine
          python3 -m twine upload --repository pypi artifacts/dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
