name: release

on:
  # Run only on push to main with a release tag
  push:
    branches: [ main ]
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  # Publish packages to PyPi
  package-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(vars.PYTHON_VERSIONS) }}
    steps:
      - name: Prepare python env
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts.python${{ matrix.python-version }}
          path: artifacts
      - name: Push package to PyPi
        run: |
          python3 -m pip install --user --upgrade twine
          python3 -m twine upload --repository pypi artifacts/dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
